### ISSUE TITLE
After upgrading ganache to 1.2.3 it closes unexpectedly while running test suites

### ISSUE THREAD

**Issue by balajipachai** [trufflesuite/ganache-ui#1077]
Error: nonce generation function failed or private key is invalid
    at Object.exports.ecsign (/node_modules/ganache-core/node_modules/ethereumjs-util/dist/index.js:369:23)
    at Transaction.sign (/node_modules/ganache-core/node_modules/ethereumjs-tx/es5/index.js:252:23)
    at Transaction.sign (/node_modules/ganache-core/lib/utils/transaction.js:260:10)
    at Transaction.hash (/node_modules/ganache-core/node_modules/ethereumjs-tx/fake.js:66:12)
    at Transaction.fakeHash [as hash] (/node_modules/ganache-core/lib/utils/transaction.js:17:51)
    at RuntimeError.combine (/node_modules/ganache-core/lib/utils/runtimeerror.js:42:30)
    at new RuntimeError (/node_modules/ganache-core/lib/utils/runtimeerror.js:19:8)
    at Function.RuntimeError.fromResults (/node_modules/ganache-core/lib/utils/runtimeerror.js:89:13)
    at /node_modules/ganache-core/lib/blockchain_double.js:527:30
    at /node_modules/ganache-core/node_modules/ethereumjs-vm/dist/runTx.js:44:5
    at /node_modules/ganache-core/node_modules/async/dist/async.js:3888:9
    at /node_modules/ganache-core/node_modules/async/dist/async.js:473:16
    at replenish (/node_modules/ganache-core/node_modules/async/dist/async.js:1006:25)
    at iterateeCallback (/node_modules/ganache-core/node_modules/async/dist/async.js:995:17)
    at /node_modules/ganache-core/node_modules/async/dist/async.js:969:16
    at /node_modules/ganache-core/node_modules/async/dist/async.js:3885:13
    at /node_modules/ganache-core/node_modules/ethereumjs-vm/dist/runTx.js:194:7
    at /node_modules/ganache-core/node_modules/ethereumjs-vm/dist/cache.js:110:7
    at /node_modules/ganache-core/node_modules/async/dist/async.js:473:16
    at replenish (/node_modules/ganache-core/node_modules/async/dist/async.js:1006:25)
    at /node_modules/ganache-core/node_modules/async/dist/async.js:1016:9
    at eachLimit$1 (/node_modules/ganache-core/node_modules/async/dist/async.js:3196:24)

**Comment by davidmurdoch** [comment]
Thanks for filing the issue, @balajipachai! Can you provide more info about your test that is failing?

**Comment by balajipachai** [comment]
I have a solidity contract with a deposit() function in it and when I am running the the truffle test suite against the same using ` it('Should revert when msg.sender is address(0)', async () => {
                    await customAssert.assertRevert(escrowInstance.deposit(100, {from: zeroAddAcc, gas: 3000000}))
                })`

Then the ganache stops and throws above error.

**Comment by davidmurdoch** [comment]
Any chance you can provide your `deposit` function implementation (at least up to the `revert` call) here or provide a minimal reproduction of the issue?

I cannot reproduce with the following contract:

```
pragma solidity ^0.4.18;

contract Revert {
  function deposit(uint val) public {
    revert();
  }
}
```

**Comment by balajipachai** [comment]
`function deposit( uint256 amount ) public 

{
        require(msg.sender != address(0), "in Escrow:deposit(). Payee cannot be address(0).");
        require(amount != 0, "in Escrow:deposit(). Amount to deposit is 0 or less than 0.");
        uint256 contractBalance = getBalance(ERC20_TOKEN, address(this));
        uint256 amountThatCanBeDeposited = DEPOSIT_AMOUNT.sub(contractBalance);
        if (amount > amountThatCanBeDeposited) {
            amount = amountThatCanBeDeposited;
        }
emit Deposited(msg.sender, amount);}`
