### ISSUE TITLE
System Error when running Ganache 2.1.0 on linux

### ISSUE THREAD

**Issue by vdegrandpre** [trufflesuite/ganache-ui#1424]
Accessing a reverted transaction causes a crash of Ganache.

PLATFORM: linux
GANACHE VERSION: 2.1.0

EXCEPTION:
```
TypeError: Cannot read property 'stack' of undefined
    at EventEmitter.<anonymous> (/src/main/main.js:259:30)
    at Generator.throw (<anonymous>)
    at step (/src/main/main.js:71:191)
    at /src/main/main.js:71:402
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

APPLICATION LOG:
```
T+0ms: eth_unsubscribe
T+0ms: eth_unsubscribe
T+9ms: eth_unsubscribe
T+9ms: eth_unsubscribe
T+9ms: eth_unsubscribe
T+1692ms: Starting server (version 2.1.0) with initial configuration: {"gasLimit":6721975,"gasPrice":20000000000,"hardfork":"petersburg","hostname":"127.0.0.1","port":7545,"network_id":5777,"default_balance_ether":100000000000000000000,"total_accounts":10,"unlocked_accounts":[],"locked":false,"vmErrorsOnRPCResponse":true,"verbose":false,"db_path":"/home/vincent/.config/Ganache/workspaces/fortunate-bridge/chaindata"}
T+1761ms: Ganache started successfully!
T+1761ms: Waiting for requests...
T+1808ms: eth_subscribe
T+1808ms: eth_getLogs
T+1808ms: eth_subscribe
T+14318ms: net_version
T+14324ms: eth_accounts
T+14348ms: eth_getBlockByNumber
T+14355ms: eth_accounts
T+14366ms: net_version
T+14376ms: eth_getBlockByNumber
T+14383ms: eth_getBlockByNumber
T+14398ms: net_version
T+14418ms: eth_getBlockByNumber
T+14432ms: eth_estimateGas
T+14438ms: net_version
T+14445ms: eth_blockNumber
T+14452ms: eth_getBlockByNumber
T+14468ms: eth_sendTransaction
T+16143ms:   Transaction: 0xae8cf664ff7e85dace03fbe4c4939e67c811263cc75a94643e0b0122dbf744b3
T+16143ms:   Contract created: 0x70ca468e5b9a9ca0f7f57db920eec7ab940915fa
T+16143ms:   Gas usage: 261393
T+16143ms:   Block Number: 1
T+16153ms:   Block Time: Mon Sep 02 2019 18:13:53 GMT-0400 (EDT)
T+16153ms: eth_getBlockByNumber
T+16158ms: eth_getTransactionReceipt
T+16162ms: eth_getCode
T+16167ms: eth_getTransactionByHash
T+16171ms: eth_getBlockByNumber
T+16181ms: eth_getBalance
T+16185ms: eth_getBlockByNumber
T+16189ms: eth_getBlockByNumber
T+16193ms: eth_sendTransaction
T+16203ms:   Transaction: 0x4e0e130b0d84c3ec9e11ba42b3c159670a9d9425861183ecbbd030dcff57a312
T+16203ms:   Gas usage: 42023
T+16203ms:   Block Number: 2
T+16203ms:   Block Time: Mon Sep 02 2019 18:13:53 GMT-0400 (EDT)
T+16207ms: eth_getBlockByNumber
T+16212ms: eth_getTransactionReceipt
T+16217ms: eth_getBlockByNumber
T+16223ms: eth_accounts
T+16233ms: net_version
T+16239ms: eth_getBlockByNumber
T+16245ms: eth_getBlockByNumber
T+16250ms: net_version
T+16261ms: eth_getBlockByNumber
T+16266ms: eth_estimateGas
T+16271ms: net_version
T+16271ms: eth_blockNumber
T+16276ms: eth_getBlockByNumber
T+16286ms: eth_sendTransaction
T+16338ms:   Transaction: 0x4ecc9f27d7c7a99ab6b52792f012f9cdc4cc462cc01aac140c4250b123744917
T+16338ms:   Contract created: 0xf38dcc7d627f35afe7d560a8cb9bc79e3da5dd30
T+16338ms:   Gas usage: 1272813
T+16338ms:   Block Number: 3
T+16338ms:   Block Time: Mon Sep 02 2019 18:13:54 GMT-0400 (EDT)
T+16338ms: eth_getBlockByNumber
T+16338ms: eth_getTransactionReceipt
T+16338ms: eth_getCode
T+16338ms: eth_getTransactionByHash
T+16338ms: eth_getBlockByNumber
T+16338ms: eth_getBalance
T+16391ms: eth_getBlockByNumber
T+16391ms: eth_getBlockByNumber
T+16391ms: eth_sendTransaction
T+16391ms:   Transaction: 0x3e12ec3d4b7a32cb85a150a16fda79d34d2af094c9d3e8cd51b1d8f8cb6ad184
T+16391ms:   Gas usage: 27023
T+16391ms:   Block Number: 4
T+16391ms:   Block Time: Mon Sep 02 2019 18:13:54 GMT-0400 (EDT)
T+16391ms: eth_getBlockByNumber
T+16391ms: eth_getTransactionReceipt
T+33833ms: net_version
T+33839ms: eth_accounts
T+33851ms: eth_accounts
T+48400ms: eth_getBlockByNumber
T+59947ms: eth_getBlockByNumber
T+59978ms: eth_call
T+73614ms: eth_accounts
T+84508ms: eth_getBlockByNumber
T+84523ms: eth_sendTransaction
T+84994ms:   Transaction: 0x9525fa6073b07cf25155252748c6cefe2b006720e22f0ff0ea39f049d4b07617
T+84994ms:   Gas usage: 21070
T+84994ms:   Block Number: 5
T+84994ms:   Block Time: Mon Sep 02 2019 18:15:03 GMT-0400 (EDT)
T+84999ms:   Runtime Error: revert
T+85004ms: eth_getBlockByNumber
T+85013ms: eth_call
T+94668ms: eth_getBlockByNumber
T+94687ms: eth_sendTransaction
T+95098ms:   Transaction: 0x1932db58f4fb3d1bfb03158f747f4d5815302bcaf2d73496b37d244e44c74e28
T+95098ms:   Gas usage: 21070
T+95098ms:   Block Number: 6
T+95107ms:   Block Time: Mon Sep 02 2019 18:15:14 GMT-0400 (EDT)
T+95107ms:   Runtime Error: revert
T+95112ms: eth_getBlockByNumber
T+95117ms: eth_call
T+158065ms: net_version
T+158077ms: eth_getCode
T+158085ms: eth_getBlockByNumber
T+158096ms: eth_getBalance
T+158103ms: eth_getTransactionCount
T+158115ms: eth_getStorageAt
T+158123ms: eth_getStorageAt
T+158137ms: eth_getStorageAt
T+158144ms: eth_getStorageAt
T+173801ms: net_version
T+173811ms: eth_getCode
```

**Comment by vdegrandpre** [comment]
The contract is ERC20, ERC20Detailed from OpenZeppelin. Was deployed, then a call to send(address, amount) will fail with the trace below :

`truffle(development)> _i.send(accounts[2], 12)
Thrown:
Error: Returned error: VM Exception while processing transaction: revert
    at XMLHttpRequest._onHttpResponseEnd (/home/vincent/.nvm/versions/node/v10.16.3/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:318:1)
    at XMLHttpRequest._setReadyState (/home/vincent/.nvm/versions/node/v10.16.3/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/home/vincent/.nvm/versions/node/v10.16.3/lib/node_modules/truffle/build/webpack:/~/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest.request.onreadystatechange (/home/vincent/.nvm/versions/node/v10.16.3/lib/node_modules/truffle/build/webpack:/~/web3-providers-http/src/index.js:96:1)
    at /home/vincent/.nvm/versions/node/v10.16.3/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:112:1
    at /home/vincent/.nvm/versions/node/v10.16.3/lib/node_modules/truffle/build/webpack:/~/web3-core-requestmanager/src/index.js:140:1
    at Object.ErrorResponse (/home/vincent/.nvm/versions/node/v10.16.3/lib/node_modules/truffle/build/webpack:/~/web3-core-helpers/src/errors.js:29:1)`

Contract source code is :

`pragma solidity >=0.5.0;

import "../node_modules/@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "../node_modules/@openzeppelin/contracts/token/ERC20/ERC20Detailed.sol";

contract VdeGTest is ERC20, ERC20Detailed {
	constructor() ERC20Detailed("VdeGTest", "VDEGTEST2", 18) public {
        _mint(msg.sender, 100000000000000);
    }

	event prout(address individu, bool heureux);
}`

Versions are :

`truffle(development)> version
Truffle v5.0.34 (core: 5.0.34)
Solidity v0.5.8 (solc-js)
Node v10.16.3
Web3.js v1.2.1`
