### ISSUE TITLE
Decoding Error when running Ganache 2.5.4 on darwin

### ISSUE THREAD

**Issue by cloutiertyler** [trufflesuite/ganache-ui#3037]
Just deployed a very simple ERC20 contract based off OpenZeppelin

PLATFORM: darwin
GANACHE VERSION: 2.5.4

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 1279$ of contract$ Lambda (ID 1504)
    at /Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:178:59)
    at Object.getStorageAllocations (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/interface/contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by dgabriel999** [comment]
Have you come up with a solution for this problem, I am having the same one. Let me know. If I find a solution I will let you know. Also, I'm creating an ERC721 token, but I wouldn't be surprised if they need the same solution.
