### ISSUE TITLE
System Error after running Ganache 2.5.4 on darwin

### ISSUE THREAD

**Issue by wh-sadalmelik** [trufflesuite/ganache-ui#3044]
PLATFORM: darwin
GANACHE VERSION: 2.5.4

EXCEPTION:
```
UnknownBaseContractIdError: Cannot locate base contract ID 1444$ of contract$ PixelToken (ID 44)
    at /Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:181:13
    at Array.map (<anonymous>)
    at allocateContract (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:178:59)
    at Object.getStorageAllocations (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/allocate/storage.ts:23:19)
    at TruffleContractDecoder.<anonymous> (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/lib/interface/contract-decoder.ts:237:39)
    at Generator.next (<anonymous>)
    at fulfilled (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/@truffle/decoder/dist/interface/contract-decoder.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by ceo-ooo-ooo** [comment]
VERSION 2.5.4 (2.5.4.1367)
Mac OS Big Sur


When you go to the Events page
<img width="1201" alt="Снимок экрана 2021-09-14 в 01 23 39" src="https://user-images.githubusercontent.com/8051759/133164194-fc80f400-b701-4428-80a6-0604b18c2718.png">

Encoded event 😔 When I go to the event itself, the error is:
<img width="1200" alt="Снимок экрана 2021-09-14 в 01 25 58" src="https://user-images.githubusercontent.com/8051759/133164394-8ce732da-257a-4fdc-b27d-eb33edaaccf3.png">

Would you like to understand this is a problem (Ganache) parse events or a problem with my code? I would be grateful for different versions

**Comment by culnaen** [comment]
I deleted the /build directory and recompiled the contracts. After that the events in Ganache were decoded and the error disappeared

**Comment by Hsu-ken** [comment]
> I deleted the /build directory and recompiled the contracts. After that the events in Ganache were decoded and the error disappeared

work for me
