### ISSUE TITLE
System Error when running Ganache 2.5.4 on darwin (not accouns)

### ISSUE THREAD

**Issue by ropstens** [trufflesuite/ganache-ui#3608]
Not Accounts.

<img width="1193" alt="not" src="https://user-images.githubusercontent.com/96194553/146220185-c2a0a858-9a33-4768-8f89-bab82d601bd8.png">

<img width="1193" alt="error" src="https://user-images.githubusercontent.com/96194553/146220351-b9fb79c7-113d-4fd8-b2c5-32ef91a8f260.png">

PLATFORM: darwin
GANACHE VERSION: 2.5.4

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/web3-providers-ws/src/index.js:282:18)
    at Timeout._onTimeout (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/web3-providers-ws/src/index.js:267:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by ropstens** [comment]
I solved the problem.

VPN Kill Switch - Off

![VPN](https://user-images.githubusercontent.com/96194553/146454785-ae35d310-b7db-4a54-a087-ccfd9afa52be.png)
