### ISSUE TITLE
System Error when running Ganache 2.6.0-beta.3 on win32

### ISSUE THREAD

**Issue by frankbonnet** [trufflesuite/ganache-ui#3748]
PLATFORM: win32
GANACHE VERSION: 2.6.0-beta.3

EXCEPTION:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at Object.extname (path.js:753:5)
    at ProjectFsWatcher.handleContractFileEvent (C:\Users\frank\AppData\Local\Programs\Ganache\resources\static\node\truffle-integration\projectFsWatcher.js:155:28)
    at FSWatcher.<anonymous> (C:\Users\frank\AppData\Local\Programs\Ganache\resources\static\node\truffle-integration\projectFsWatcher.js:186:16)
    at FSWatcher.emit (events.js:210:5)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:131:12)
```

**Comment by SmarakNayak** [comment]
Bit of a hack but I managed to avoid the error by wrapping `handleContractFileEvent()` in try-catch within projectFsWatcher.js

```
  handleContractFileEvent(eventType, filename) {
    try {
      const extension = path.extname(filename);
      if (extension === ".json") {
        if (eventType === "rename") {
          if (this.contractExists(filename)) {
            // created
            this.fileToContractIdx[filename] = this.contracts.length;
            const contract = this.readContract(filename);
            this.contracts.push(contract);
          } else {
            // deleted
            this.contracts.splice(this.fileToContractIdx[filename]);
            delete this.fileToContractIdx[filename];
          }
        } else if (eventType === "change") {
          // modified
          const contract = this.readContract(filename);
          this.contracts[this.fileToContractIdx[filename]] = contract;
        }
      }
    }  catch (e) {
      return null;
    }
  }

```

**Comment by cheffNFT** [comment]
sorry I have no idea what are you talking about I'm having the same error using truffle and it just crashes completely

**Comment by SmarakNayak** [comment]
Go to your C:\Users\<User Name Here>\AppData\Local\Programs\Ganache\resources\static\node\truffle-integration\projectFsWatcher.js file & replace the handleContractFileEvent() function with my modified version above. Should be on line 154 depending on your version of ganache.

Hopefully that helps!
