### ISSUE TITLE
System Error when running Ganache 2.5.4 on win32

### ISSUE THREAD

**Issue by meta-avi** [trufflesuite/ganache-ui#4344]
![ganache error msg](https://user-images.githubusercontent.com/95247924/160537549-e68f86ed-a93d-4f49-aa58-b80b8d509d91.JPG)

PLATFORM: win32
GANACHE VERSION: 2.5.4

EXCEPTION:
```
Error: corda bootstrapper child process exited with code 1.

Stderr:
No nodes found


Stdout:
2022-03-29 05:59:28,925 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2022-03-29 05:59:28,934 main WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
Bootstrapping local test network in C:\Users\avi\AppData\Roaming\Ganache\workspaces\Quickstart\chaindata


Error:


config:{"env":{"PATH":"C:\\Users\\avi\\AppData\\Roaming\\Ganache\\extras\\OpenJDK8U-jre_x64_windows_hotspot_8u232b09\\bin","CAPSULE_CACHE_DIR":"./capsule"},"cwd":"C:\\Users\\avi\\AppData\\Roaming\\Ganache\\workspaces\\Quickstart\\chaindata"}
    at CordaBootstrap.handleClose (C:\Users\avi\Desktop\Ganache-2.5.4-win-x64\app\resources\app.asar\webpack:\src\integrations\corda\main\utils\network\bootstrap.js:120:27)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by meta-avi** [comment]
kindly assist me , as the above is the error message i get when i try launching the Ganache application
