### ISSUE TITLE
UI release image is broken: latest-linux.yml cannot be downloaded

### ISSUE THREAD

**Issue by kirillt** [trufflesuite/ganache-ui#5122]
I've downloaded the AppImage from https://trufflesuite.com/ganache/
```
$ chmod +x ganache-2.5.4-linux-x86_64.AppImage
$ ./ganache-2.5.4-linux-x86_64.AppImage
13:52:31.469 › Checking for update
13:52:34.065 › Error: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/trufflesuite/ganache/releases/download/v7.5.0/latest-linux.yml): HttpError: 404 
"method: GET url: https://github.com/trufflesuite/ganache/releases/download/v7.5.0/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "status": "404",
  "server": "GitHub.com",
  "date": "Mon, 05 Dec 2022 10:52:33 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "A8D6:1132:6D2AE11:7144156:638DCD71"
}
    at createHttpError (/tmp/.mount_ganachiwN9C1/resources/app.asar/webpack:/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_ganachiwN9C1/resources/app.asar/webpack:/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:168:14)
    at ClientRequest.<anonymous> (/tmp/.mount_ganachiwN9C1/resources/app.asar/webpack:/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:210:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2510:12)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
    at newError (/tmp/.mount_ganachiwN9C1/resources/app.asar/webpack:/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:212:17)
    at GitHubProvider.getLatestVersion (/tmp/.mount_ganachiwN9C1/resources/app.asar/webpack:/node_modules/electron-updater/out/providers/GitHubProvider.js:134:41)
```

The error states it could not download https://github.com/trufflesuite/ganache/releases/download/v7.5.0/latest-linux.yml, and indeed when I open release 7.5.0 page there is only source code available.

Is AppImage format still supported?

**Comment by davidmurdoch** [comment]
This repository was previously used for Ganache UI, it is now for the npm package `ganache`. Ganache UI is here: https://github.com/trufflesuite/ganache-ui . Ganache UI currently pings this repo when starting up in order to determine if it should notify the user of a new version or not, but since this repo is no longer the correct repo it shows an error. The Error you see on the CLI is an _internal_ error that can be ignored; Ganache UI's stdio is not intended for end-users.

v2.5.4 _is_ the latest release for Ganache UI. Work is in currently progress to update it. The next release of Ganache UI will fix this internal error.
