### ISSUE TITLE
Error: connection not open     at WebsocketProvider.send (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\web3-providers-ws\src\index.js:282:18)     at Timeout._onTimeout (C:\Program Files\WindowsApps\GanacheUI_2.5.4.0_x64__5dg5pnz03psnj\app\resources\static\node\node_modules\web3-providers-ws\src\index.js:267:19)     at listOnTimeout (internal/timers.js:531:17)     at processTimers (internal/timers.js:475:7)

### ISSUE THREAD

**Issue by parwejkhan1816** [trufflesuite/ganache-ui#5257]

**Comment by jeffsmale90** [comment]
Thanks @parwejkhan1816 for raising this issue! We have a beta release out https://github.com/trufflesuite/ganache-ui/releases/tag/v2.7.0-beta which brings Ganache v7 as the underlying ethereum simulator. Can you please try installing this and let us know whether it fixes the issue?

Thanks!
