### ISSUE TITLE
Error raised when decoding an event, if the related contract doesn't define the event

### ISSUE THREAD

**Issue by akf0rce** [trufflesuite/ganache-ui#5296]
PLATFORM: darwin
GANACHE VERSION: 2.7.0

EXCEPTION:
```
TypeError: Cannot read property 'stack' of undefined
    at IpcMainImpl.<anonymous> (/webpack:/src/integrations/ethereum/index.js:76:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jeffsmale90** [comment]
I've posted a reproduction of this issue here: https://github.com/jeffsmale90/ganache-ui-stack-repro, I'll be working on a fix next.
