### ISSUE TITLE
Error when trying to fork Binance Smart Chain

### ISSUE THREAD

**Issue by x1250** [trufflesuite/ganache-ui#5342]
Trying to fork binance smart chain:

PLATFORM: linux
GANACHE VERSION: 2.7.0

EXCEPTION:
```
Error: the resource eth_getTransactionCount is not available.
    at /tmp/.mount_ganachC0Kwi8/resources/static/node/node_modules/ganache/dist/node/1.js:2:23076
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async HttpHandler.queueRequest (/tmp/.mount_ganachC0Kwi8/resources/static/node/node_modules/ganache/dist/node/1.js:2:23229)
    at async HttpHandler.request (/tmp/.mount_ganachC0Kwi8/resources/static/node/node_modules/ganache/dist/node/1.js:2:106985)
    at async fetchNonce (/tmp/.mount_ganachC0Kwi8/resources/static/node/node_modules/ganache/dist/node/1.js:2:149360)
    at async /tmp/.mount_ganachC0Kwi8/resources/static/node/node_modules/ganache/dist/node/1.js:2:149313
    at async Promise.all (index 0)
    at async /tmp/.mount_ganachC0Kwi8/resources/static/node/node_modules/ganache/dist/node/1.js:2:148805
    at async Promise.all (index 0)
    at async Fork.<anonymous> (/tmp/.mount_ganachC0Kwi8/resources/static/node/node_modules/ganache/dist/node/1.js:2:148724)
```

**Comment by davidmurdoch** [comment]
This is a binance issue.
