### ISSUE TITLE
System Error when running Ganache 2.7.0 on darwin

### ISSUE THREAD

**Issue by waypost** [trufflesuite/ganache-ui#5350]
Steps to recreate:

New workspace  > Server > Chain Forking > Paste HTTP provider URL from Quicknode > Start

I've tried creating a new endpoint, but still receive the same error.

PLATFORM: darwin
GANACHE VERSION: 2.7.0

EXCEPTION:
```
Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)
```

**Comment by waypost** [comment]
Note: I tested with an endpoint created on Infura, and it works fine.
