### ISSUE TITLE
System Error when running Ganache 2.7.0 on darwin

### ISSUE THREAD

**Issue by Ypomerantsev** [trufflesuite/ganache-ui#5352]
Exception raises, when I try to send money using my MetaMask test account to a MetaCoin smart contract.
Steps to reproduce:
1. Clean install latest version of Truffle , VS Code, Ganache
git version 2.40.0
Truffle v5.8.1 (core: 5.8.1)
Ganache v7.7.7
Solidity v0.5.16 (solc-js)
Node v16.19.1
Web3.js v1.8.2
2. run truffle MetaCoin example and deploy smart contracts into Ganache
truffle unbox metacoin
3. run truffle test using metacoin.js and TestMetaCoin.sol
4. run truffle dashboard
5. connect MetaMask wallet to an account created by Ganeche
6. send any amount to public address "MetaCoin" smart contract using MetaMask (I receive transaction fail error in MetaMask, see screenshot attached) and then go to Ganeche UI and try to look into the same transaction made to the same "MetaCoin" contract.

<img width="1198" alt="Screenshot 2023-03-26 at 3 56 21 AM" src="https://user-images.githubusercontent.com/32407032/227765534-b8f034e0-f993-4de8-97dc-8280b2f05f86.png">

PLATFORM: darwin
GANACHE VERSION: 2.7.0

EXCEPTION:
```
TypeError: Cannot read property 'stack' of undefined
    at IpcMainImpl.<anonymous> (/webpack:/src/integrations/ethereum/index.js:96:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Ypomerantsev** [comment]
After I try to send money I receive this error in MetaMask:
<img width="660" alt="Screenshot 2023-03-26 at 4 21 12 AM" src="https://user-images.githubusercontent.com/32407032/227766557-c64ac7a9-ea72-4206-8552-a4baa41c17c9.png">
Then, I go to Ganache UI and jump into contract and see the transcation:
<img width="1196" alt="Screenshot 2023-03-26 at 4 17 45 AM" src="https://user-images.githubusercontent.com/32407032/227766483-d03b667b-17a3-411e-b577-7d1bba7db6dd.png">

When I click on transaction to get details, I receive this error:
<img width="619" alt="Screenshot 2023-03-26 at 4 18 14 AM" src="https://user-images.githubusercontent.com/32407032/227766487-3897fd4b-aff6-42d3-a5cf-99548ea987f8.png">

**Comment by Ypomerantsev** [comment]
Hello, will you prioritize this bug?

**Comment by davidmurdoch** [comment]
Can you try the beta release and let us know if that fixes it?: https://github.com/trufflesuite/ganache-ui/releases/tag/v2.7.1-beta
