### ISSUE TITLE
Decoding Error when running Ganache 2.7.0 on win32

### ISSUE THREAD

**Issue by Shitalkachare** [trufflesuite/ganache-ui#5382]
PLATFORM: win32
GANACHE VERSION: 2.7.0

EXCEPTION:
```
Error: connection not open
    at WebsocketProvider.send (C:\Program Files\WindowsApps\GanacheUI_2.7.0.0_x64__rb4352f0jd4m2\app\resources\static\node\node_modules\@truffle\decoder\node_modules\web3-providers-ws\src\index.js:282:18)
    at Timeout._onTimeout (C:\Program Files\WindowsApps\GanacheUI_2.7.0.0_x64__rb4352f0jd4m2\app\resources\static\node\node_modules\@truffle\decoder\node_modules\web3-providers-ws\src\index.js:267:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

**Comment by jeffsmale90** [comment]
Hi @Shitalkachare - thanks for raising this issue. I believe it is fixed by our latest release, which has just gone out https://github.com/trufflesuite/ganache-ui/releases/tag/v2.7.1-beta, can you please download this and see if it fixes the problem for you?

Thanks!

**Comment by jeffsmale90** [comment]
@Shitalkachare sorry about the mention - I commented on the wrong issue! I deleted the offending comment.

Thanks for raising the issue - I'll look into this when I get a chance.
