### ISSUE TITLE
System Error when running Ganache 2.7.0 on linux

### ISSUE THREAD

**Issue by amadousysada** [trufflesuite/ganache-ui#5383]
PLATFORM: linux
GANACHE VERSION: 2.7.0

EXCEPTION:
```
TypeError: Cannot read property 'stack' of undefined
    at IpcMainImpl.<anonymous> (/webpack:/src/integrations/ethereum/index.js:96:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jeffsmale90** [comment]
Hi @amadousysada  - thanks for raising this issue. I believe it is fixed by our latest release, which has just gone out https://github.com/trufflesuite/ganache-ui/releases/tag/v2.7.1-beta, can you please download this and see if it fixes the problem for you?

Thanks!
