### ISSUE TITLE
System Error when running Ganache 2.7.0 on win32

### ISSUE THREAD

**Issue by jizew** [trufflesuite/ganache-ui#5391]
PLATFORM: win32
GANACHE VERSION: 2.7.0

EXCEPTION:
```
Error: EXDEV: cross-device link not permitted, rename 'C:\Users\Administrator\AppData\Roaming\Ganache\ui\global\Settings.3188813437' -> 'C:\Users\Administrator\AppData\Roaming\Ganache\ui\global\Settings'
    at Object.renameSync (fs.js:772:3)
    at writeFileSync (D:\WindowsApps\GanacheUI_2.7.0.0_x64__rb4352f0jd4m2\app\resources\app.asar\node_modules\write-file-atomic\index.js:124:8)
    at Proxy.setItem (D:\WindowsApps\GanacheUI_2.7.0.0_x64__rb4352f0jd4m2\app\resources\app.asar\node_modules\node-localstorage\LocalStorage.js:217:7)
    at JsonStorage_JsonStorage.setToStorage (D:\WindowsApps\GanacheUI_2.7.0.0_x64__rb4352f0jd4m2\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:48:18)
    at JsonStorage_JsonStorage.setAll (D:\WindowsApps\GanacheUI_2.7.0.0_x64__rb4352f0jd4m2\app\resources\app.asar\webpack:\src\main\types\json\JsonStorage.js:58:10)
    at GlobalSettings_GlobalSettings.setAll (D:\WindowsApps\GanacheUI_2.7.0.0_x64__rb4352f0jd4m2\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:55:19)
    at GlobalSettings_GlobalSettings.bootstrap (D:\WindowsApps\GanacheUI_2.7.0.0_x64__rb4352f0jd4m2\app\resources\app.asar\webpack:\src\main\types\settings\Settings.js:87:10)
    at GlobalSettings_GlobalSettings.bootstrap (D:\WindowsApps\GanacheUI_2.7.0.0_x64__rb4352f0jd4m2\app\resources\app.asar\webpack:\src\main\types\settings\GlobalSettings.js:15:11)
    at D:\WindowsApps\GanacheUI_2.7.0.0_x64__rb4352f0jd4m2\app\resources\app.asar\webpack:\src\main\index.js:241:12
```

**Comment by jizew** [comment]
It has been fixed through upgrading to 2.7.1 beta,as https://github.com/trufflesuite/ganache-ui/releases/tag/v2.7.1-beta
